config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
      mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
    end
  post "/graphql", to: "graphql#execute"
  root 'bloggs#index'
  resources :bloggs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blogg.rb
class Blogg < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bloggs_controller.rb
class BloggsController < ApplicationController
  before_action :set_blogg, only: %i[ show edit update destroy ]

  # GET /bloggs or /bloggs.json
  def index
    @bloggs = Blogg.all
  end

  # GET /bloggs/1 or /bloggs/1.json
  def show
  end

  # GET /bloggs/new
  def new
    @blogg = Blogg.new
  end

  # GET /bloggs/1/edit
  def edit
  end

  # POST /bloggs or /bloggs.json
  def create
    @blogg = Blogg.new(blogg_params)

    respond_to do |format|
      if @blogg.save
        format.html { redirect_to @blogg, notice: "Blogg was successfully created." }
        format.json { render :show, status: :created, location: @blogg }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blogg.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bloggs/1 or /bloggs/1.json
  def update
    respond_to do |format|
      if @blogg.update(blogg_params)
        format.html { redirect_to @blogg, notice: "Blogg was successfully updated." }
        format.json { render :show, status: :ok, location: @blogg }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blogg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bloggs/1 or /bloggs/1.json
  def destroy
    @blogg.destroy
    respond_to do |format|
      format.html { redirect_to bloggs_url, notice: "Blogg was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blogg
      @blogg = Blogg.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blogg_params
      params.require(:blogg).permit(:title, :content)
    end
end

app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController
  def execute
    variables = ensure_hash(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
      blog: Blogg.first
    }
    result = BlogSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  end

  private

  # Handle form data, JSON body, or a blank value
  def ensure_hash(ambiguous_param)
    case ambiguous_param
    when String
      if ambiguous_param.present?
        ensure_hash(JSON.parse(ambiguous_param))
      else
        {}
      end
    when Hash, ActionController::Parameters
      ambiguous_param
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{ambiguous_param}"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bloggs_helper.rb
module BloggsHelper
end

app/views/bloggs/_form.html.erb
<%= form_with(model: blogg, local: true) do |form| %>
  <% if blogg.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blogg.errors.count, "error") %> prohibited this blogg from being saved:</h2>

      <ul>
        <% blogg.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bloggs/edit.html.erb
<h1>Editing Blogg</h1>

<%= render 'form', blogg: @blogg %>

<%= link_to 'Show', @blogg %> |
<%= link_to 'Back', bloggs_path %>

app/views/bloggs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bloggs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bloggs.each do |blogg| %>
      <tr>
        <td><%= blogg.title %></td>
        <td><%= blogg.content %></td>
        <td><%= link_to 'Show', blogg %></td>
        <td><%= link_to 'Edit', edit_blogg_path(blogg) %></td>
        <td><%= link_to 'Destroy', blogg, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blogg', new_blogg_path %>

app/views/bloggs/new.html.erb
<h1>New Blogg</h1>

<%= render 'form', blogg: @blogg %>

<%= link_to 'Back', bloggs_path %>

app/views/bloggs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blogg.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blogg.content %>
</p>

<%= link_to 'Edit', edit_blogg_path(@blogg) %> |
<%= link_to 'Back', bloggs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>